### ISSUE TITLE
Readme 

### ISSUE THREAD

**Issue by ssurbhi09** [ssurbhi09/Link_tree#1]
Description of this project in readme file.

**Comment by shivi2912** [comment]
I want to work on this..

**Comment by ssurbhi09** [comment]
Yes u can 
Assign @shivi2912

**Comment by shivi2912** [comment]
thanks...I am working on it..

**Comment by shivi2912** [comment]
this project was not the part of hacktoberfest?  :/

**Comment by ssurbhi09** [comment]
What happen?

**Comment by shivi2912** [comment]
This project has hacktoberfest label, It doesn't contain...hacktoberfest tag .
![hacktober](https://user-images.githubusercontent.com/91618828/136265612-2e9fe3e8-7151-4109-831c-d524361a246a.png)
..

**Comment by ssurbhi09** [comment]
added the hacktoberfest to the above issues, thanks again @razzeee for suggesting it!

**Comment by ssurbhi09** [comment]
Added [Hacktoberfest]()

**Comment by ssurbhi09** [comment]
already added 
![Screenshot_20211007-003251__01](https://user-images.githubusercontent.com/79759981/136266825-fd1b0b58-96f8-40a8-96d6-df440dd4ed75.jpg)

**Comment by shivi2912** [comment]
mam this are labels.
![tag](https://user-images.githubusercontent.com/91618828/136267280-e042aac0-f8d0-4569-89f4-625a8895ae8c.png)
..

**Comment by shivi2912** [comment]
please add here in both your both Repos
![tag](https://user-images.githubusercontent.com/91618828/136267440-9f4a2c92-7a2f-44e2-942f-1c7b6624def8.png)
.

**Comment by shivi2912** [comment]
For my PR to be accepted in fest....it needs a "hacktober-accepted" on it.
![pr](https://user-images.githubusercontent.com/91618828/136268391-a9222ea0-6b54-412e-9cb5-da2d43baa6f9.png)

heree
